package domain

type CalCmsPgmData struct {
	Jobs             []any  `json:"jobs"`
	EventCount       string `json:"event_count"`
	Month            string `json:"month"`
	ModifiedAt       string `json:"modified_at"`
	LocalBaseURL     string `json:"local_base_url"`
	ProjectColoradio int    `json:"project_coloradio"`
	ProjectImage     string `json:"project_image"`
	Order            string `json:"order"`
	Weekday          string `json:"weekday"`
	Get              string `json:"get"`
	Events           []struct {
		PodcastURL                 string `json:"podcast_url"`
		Thumb                      string `json:"thumb"`
		FullTitle                  string `json:"full_title"`
		TimeZone                   string `json:"time_zone"`
		ProjectSubtitle            string `json:"project_subtitle"`
		StartDay                   string `json:"start_day"`
		WeekdayName                string `json:"weekday_name"`
		UtcOffset                  string `json:"utc_offset"`
		EndDateName                string `json:"end_date_name"`
		StartUtcEpoch              int    `json:"start_utc_epoch"`
		RecurrenceCount            string `json:"recurrence_count"`
		ProjectTitle               string `json:"project_title"`
		Reference                  any    `json:"reference"`
		UserExcerpt                any    `json:"user_excerpt"`
		Dtend                      string `json:"dtend"`
		MediaURL                   any    `json:"media_url"`
		BaseURL                    any    `json:"base_url"`
		Excerpt                    string `json:"excerpt"`
		Image                      string `json:"image"`
		DisableEventSync           int    `json:"disable_event_sync"`
		ProjectEmail               string `json:"project_email"`
		Key                        string `json:"key"`
		Published                  int    `json:"published"`
		ProjectImage               string `json:"project_image"`
		Icon                       string `json:"icon"`
		EventURI                   string `json:"event_uri"`
		FullTitleNoProgram         string `json:"full_title_no_program"`
		StartTimeName              string `json:"start_time_name"`
		FullTitleNoProgramNoSeries string `json:"full_title_no_program_no_series"`
		RdsTitle                   string `json:"rds_title"`
		EndTimeName                string `json:"end_time_name"`
		Topic                      string `json:"topic"`
		StartYear                  string `json:"start_year"`
		End                        string `json:"end"`
		First                      int    `json:"__first__,omitempty"`
		Live                       int    `json:"live"`
		EventID                    string `json:"event_id"`
		StartMinute                string `json:"start_minute"`
		StartDatetime              string `json:"start_datetime"`
		EndDatetime                string `json:"end_datetime"`
		Episode                    any    `json:"episode"`
		Archived                   int    `json:"archived"`
		ModifiedBy                 string `json:"modified_by"`
		StartMonth                 string `json:"start_month"`
		Dtstart                    string `json:"dtstart"`
		CacheBaseURL               string `json:"cache_base_url"`
		ProjectName                string `json:"project_name"`
		ProjectProjectID           int    `json:"project_project_id"`
		LocationLabelStudio        int    `json:"location_label_studio"`
		StartTime                  string `json:"start_time"`
		RecurrenceCountAlpha       string `json:"recurrence_count_alpha"`
		Status                     any    `json:"status"`
		HTMLContent                string `json:"html_content"`
		TimeOfDay                  any    `json:"time_of_day"`
		Counter1                   int    `json:"counter_1,omitempty"`
		BaseDomain                 string `json:"base_domain"`
		Draft                      int    `json:"draft"`
		StartDate                  string `json:"start_date"`
		Rerun                      string `json:"rerun"`
		HTMLTopic                  string `json:"html_topic"`
		Recurrence                 int    `json:"recurrence"`
		Content                    string `json:"content"`
		EndTime                    string `json:"end_time"`
		Title                      string `json:"title"`
		ProjectStartDate           string `json:"project_start_date"`
		SeriesName                 string `json:"series_name"`
		ArchiveURL                 string `json:"archive_url"`
		Playout                    int    `json:"playout"`
		SourceBaseURL              string `json:"source_base_url"`
		ProjectEndDate             string `json:"project_end_date"`
		StartDateName              string `json:"start_date_name"`
		Start                      string `json:"start"`
		EndUtcEpoch                int    `json:"end_utc_epoch"`
		StaticFilesURL             string `json:"static_files_url"`
		FullTitleNoSeries          string `json:"full_title_no_series"`
		DayOfYear                  int    `json:"day_of_year"`
		NoImageInText              int    `json:"no_image_in_text"`
		Location                   string `json:"location"`
		WeekdayShortName           string `json:"weekday_short_name"`
		Weekday                    string `json:"weekday"`
		StartHour                  string `json:"start_hour"`
		CreatedAt                  string `json:"created_at"`
		Project                    string `json:"project"`
		Program                    any    `json:"program"`
		NoComment                  int    `json:"no_comment"`
		Day                        string `json:"day"`
		CommentCount               int    `json:"comment_count"`
		EndDate                    string `json:"end_date"`
		UserTitle                  string `json:"user_title"`
		LocationCSS                string `json:"location_css"`
		ModifiedAt                 string `json:"modified_at"`
		IsFirstOfDay               int    `json:"is_first_of_day,omitempty"`
		WeekOfYear                 int    `json:"week_of_year"`
		Counter2                   int    `json:"counter_2,omitempty"`
		Counter3                   int    `json:"counter_3,omitempty"`
		Counter4                   int    `json:"counter_4,omitempty"`
		IsRunning                  int    `json:"is_running,omitempty"`
		Counter5                   int    `json:"counter_5,omitempty"`
		Counter6                   int    `json:"counter_6,omitempty"`
		Counter7                   int    `json:"counter_7,omitempty"`
		Counter8                   int    `json:"counter_8,omitempty"`
		IsLastOfDay                int    `json:"is_last_of_day,omitempty"`
		Counter9                   int    `json:"counter_9,omitempty"`
		Last                       int    `json:"__last__,omitempty"`
	} `json:"events"`
	FirstOfList      string `json:"first_of_list"`
	FromTime         string `json:"from_time"`
	Project          string `json:"project"`
	User             any    `json:"user"`
	ExcludeProjects  string `json:"exclude_projects"`
	ProjectEmail     string `json:"project_email"`
	StaticFilesURL   string `json:"static_files_url"`
	Extern           int    `json:"extern"`
	DisableEventSync string `json:"disable_event_sync"`
	Date             string `json:"date"`
	Location         string `json:"location"`
	Recordings       string `json:"recordings"`
	StudioID         string `json:"studio_id"`
	ProjectEndDate   string `json:"project_end_date"`
	SourceBaseURL    string `json:"source_base_url"`
	ProjectID        string `json:"project_id"`
	LocalMediaURL    string `json:"local_media_url"`
	EventDtstart     string `json:"event_dtstart"`
	Search           string `json:"search"`
	ExcludeLocations string `json:"exclude_locations"`
	ProjectTitle     string `json:"project_title"`
	TillTime         string `json:"till_time"`
	JSONCallback     string `json:"json_callback"`
	Limit            string `json:"limit"`
	ProjectStartDate string `json:"project_start_date"`
	LocalArchiveURL  string `json:"local_archive_url"`
	BaseURL          string `json:"base_url"`
	SeriesName       string `json:"series_name"`
	Title            string `json:"title"`
	Time             string `json:"time"`
	Controllers      struct {
		Event    string `json:"event"`
		Events   string `json:"events"`
		Calendar string `json:"calendar"`
		Comments string `json:"comments"`
		Atom     string `json:"atom"`
		Domain   string `json:"domain"`
		Rss      string `json:"rss"`
		Ical     string `json:"ical"`
	} `json:"controllers"`
	TimeOfDay        string `json:"time_of_day"`
	UtcOffset        string `json:"utc_offset"`
	Category         string `json:"category"`
	Debug            string `json:"debug"`
	BaseDomain       string `json:"base_domain"`
	Archive          string `json:"archive"`
	ProjectSubtitle  string `json:"project_subtitle"`
	TimeZone         string `json:"time_zone"`
	ProjectProjectID int    `json:"project_project_id"`
	Tag              string `json:"tag"`
	TillDate         string `json:"till_date"`
	DefaultProject   struct {
		Name      string `json:"name"`
		Title     string `json:"title"`
		EndDate   string `json:"end_date"`
		StartDate string `json:"start_date"`
		Image     string `json:"image"`
		Subtitle  string `json:"subtitle"`
		ProjectID int    `json:"project_id"`
		Email     string `json:"email"`
	} `json:"default_project"`
	Template         string `json:"template"`
	ProjectName      string `json:"project_name"`
	CacheBaseURL     string `json:"cache_base_url"`
	FromDate         string `json:"from_date"`
	EventID          string `json:"event_id"`
	DateRangeInclude int    `json:"date_range_include"`
	StudioName       string `json:"studio_name"`
	NoExclude        string `json:"no_exclude"`
}
